### PR TITLE
add svelte example

### PR DESCRIPTION
**Pull request by kettanaito**
- Adds usage example with Svelte

## Materials

- [MSW in SvelteKit](https://flaming.codes/posts/msw-in-sveltekit-for-local-development), showcases some cool patterns but requires a standalone Node.js process to run alongside your Svelte app to enable server-side request interception.

### CODE REVIEW

**Comment by kettanaito** [comment]
## Fails to build during `test:e2e`

### Steps to reproduce

```sh
pnpm test:e2e
```

### Current behavior

```sh
[WebServer] 
[WebServer] [commonjs--resolver] No known conditions for "./browser" specifier in "msw" package
[WebServer] error during build:
Error: No known conditions for "./browser" specifier in "msw" package
    at e (/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:16649:25)
    at n (/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:16649:646)
    at o (/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:16649:1297)
    at resolveExportsOrImports (/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23407:20)
    at resolveDeepImport (/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23426:31)
    at tryNodeResolve (/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23115:20)
    at Object.resolveId (/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:22876:28)
    at Object.handler (/node_modules/.pnpm/vite@4.3.4/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:46631:19)
    at /node_modules/.pnpm/rollup@3.21.3/node_modules/rollup/dist/es/shared/node-entry.js:24533:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Process from config.webServer was not able to start. Exit code: 1
```

I think this happens because the bundler evaluates the `await import('../mocks/browser')` statement from the client-side `+layout.ts`. That code should never run during the build that happens in Node.js.

**Comment by pawelblaszczyk5** [comment]
I tried to play a bit with it, I couldn't find the problem root source unfortunately.

I'm not sure how helpful this will be but, I've found a workaround, which is also described in the SvelteKit docs. You can use the `vite-plugin-iso-import` to make sure the imports are correctly preserved/removed based on the environment. It's mentioned here: https://kit.svelte.dev/faq#how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window 

I used it with this branch and it seemed to work correctly 😃

**Comment by kettanaito** [comment]
Hey, @pawelblaszczyk5! Thank you for your help. Using that solution worked! At least, I don't see any build errors anymore. 

I'm facing a different problem related to how Svelte evaluates server-side `load` functions. It seems that it always runs root layout's and individual pages' `load` functions _in parallel_. This means that `await import('../mocks/node')` expression is never awaited before any page-level `load` functions are run (where you fetch the actual data). This results in the initial server-side request to always be performed as-is because the root-level layout's `load` hasn't finished importing MSW yet. 

You can experience that for yourself on this branch: run the app via `pnpm dev` and check the stdout of the Vite process. The order in which the `load` functions are executed is (probably?) wrong.

**Comment by pawelblaszczyk5** [comment]
Yup, SvelteKit runs the `load` methods in parallel to optimize the loading. In theory you can make them blocking but I guess it isn't the best idea to do so for MSW. I'll try to come up with some better idea for this tomorrow :)

**Comment by kettanaito** [comment]
Yeah, I suspected that much. Well, that's a shame, looks like we won't be able to utilize the loaders then. I like that approach more than the injection as showcased in the article I attached in the description above. We need to design a better server-side integration strategy then, as I don't want to ask people to run a separate Node process just to have server-side API mocking support in their Svelte apps. 

What's a bit confusing to me is why the root layout template doesn't block the rendering (and the loaders) of the child pages if you do conditional rendering?

```svelte
// +layout.svelte
{#if mocksAreReady}
<slot />
{/if}
```

This will trigger the loaders for `+page.svelte` _anyway_, despite the actual rendering of the page being deferred by some asynchronous action in the `+layout.ts`.

**Comment by pawelblaszczyk5** [comment]
The logic behind is that the load function output won't impact children load functions, hence you can start all of them in parallel. You can use some function (I don't remember the name of it, sequence or something) to block it. But I don't feel like it'd be a good pattern here. 

I think that utilizng SvelteKit hooks - to be exact the `handle` hook on server could play nicely. It runs before every single request though 🤔

**Comment by kettanaito** [comment]
I will take a look at `handle`. I suspect it's called on _dispatched_ requests so it won't work for our case (the mocks should apply during request _declaration_). Thanks for all the suggestions! Would be thankful if we kept hacking on this and get the Svelte integration to a top-notch shape together.

**Comment by pawelblaszczyk5** [comment]
Okay, it didn't give me a peace of mind so I'm working on it and I think i've got something. I'll make a PR into this branch soonish 😄 Just need to make sure everything is working correctly, and adjust it to your other examples

**Comment by pawelblaszczyk5** [comment]
I've made a PR, left a few comments to explain my work. I can further improve it if you've got any ideas or uncertanities about the solution 😇

**Comment by pawelblaszczyk5** [comment]
I see it's passing, awesome 🚀 Btw. would you be open for SolidJS example contribution?

**Pull request merged**
